// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7gRcw6NgHNI3eE1D2WXTjVOhiKXHG45s',
    appId: '1:509220172842:web:0295ad755db43da8393f53',
    messagingSenderId: '509220172842',
    projectId: 'depolamobileapp',
    authDomain: 'depolamobileapp.firebaseapp.com',
    storageBucket: 'depolamobileapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALREhkW5tTpO9KVu-ggqoRFx2UBk6Sl5Y',
    appId: '1:509220172842:android:18af3da1fa007503393f53',
    messagingSenderId: '509220172842',
    projectId: 'depolamobileapp',
    storageBucket: 'depolamobileapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCllFZdxVEBSLFceVp2TbbrRA4_xWW2evc',
    appId: '1:509220172842:ios:ab46b0e2bb2c9b54393f53',
    messagingSenderId: '509220172842',
    projectId: 'depolamobileapp',
    storageBucket: 'depolamobileapp.appspot.com',
    iosBundleId: 'com.example.depolamauygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCllFZdxVEBSLFceVp2TbbrRA4_xWW2evc',
    appId: '1:509220172842:ios:84554a4c466edb29393f53',
    messagingSenderId: '509220172842',
    projectId: 'depolamobileapp',
    storageBucket: 'depolamobileapp.appspot.com',
    iosBundleId: 'com.example.depolamauygulamasi.RunnerTests',
  );
}
